import type { Metadata } from 'next';
import './globals.css';
import App from './app';
import { PublicEnvScript } from 'next-runtime-env';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <PublicEnvScript />
      </head>
      <body className={`antialiased`}>
        <App>{children}</App>
      </body>
    </html>
  );
}
